_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./output/base_15/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: "('[16,20]_train.json', )"
  TEST: ('voc_2007_test', )
  # MEMORY: '../data/voc2007/annotations/emm15_50img.json'
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (10000, 11000)
  MAX_ITER: 12000
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: './output/distill'
SEED: 9991
