_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./output/base_15/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: "('[16,20]_train.json', )"
  TEST: ('voc_2007_test', )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (3000, 4000)
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: './output/distill'
SEED: 1234
