_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "myILOD/params/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ('voc_2007_trainval', )
  TEST: ('voc_2007_test', )
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  STEPS: (30000, )
  MAX_ITER: 40000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 2500
OUTPUT_DIR: './output/base15_fasterilod'
SEED: 2333
TEST:
  EVAL_PERIOD: 3000
IOD:
  OLD_CLS: 15 
  NEW_CLS: 5
  DISTILL: False