_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_PBresnet_backbone"
  WEIGHTS: "./myILOD/params/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 20
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ('voc[1,1]_train', )
  TEST: ('voc_2007_test', )
SOLVER:
  OPTIM: "Adam"
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "./output/pb[body]voc[1,1]"
SEED: 9999
