_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./myILOD/params/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 21
DATASETS:
  TRAIN: ('voc_train', )
  TEST: ('voc_val_woDifficult', )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/voc"
SEED: 9999
