_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 21
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATASETS:
  TRAIN: ('voc[1,10]_train', )
  TEST: ('voc_2007_test', )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  # STEPS: (12000, 16000)
  # MAX_ITER: 18000
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 3000
OUTPUT_DIR: "./output/all_20"
SEED: 9999
