_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./output/base_15/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ('voc_2007_trainval', )
  TEST: ('voc_2007_test', )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (12000,16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
IOD:
  MEMORY: ()
  MEMORY_AUG: True
  DISTILL: True
  BACKBON_FEATRUE: True
  BOX_FEATRUE: True
  ROI_FEATRUE: True

OUTPUT_DIR: './output/distill'
SEED: 233
